export const FEATURES = {
  VIEW_DASHBOARD: "VIEW_DASHBOARD",
  CREATE_TEACHER: "CREATE_TEACHER",
  CREATE_STUDENT: "CREATE_STUDENT",
  MANAGE_ROLES: "MANAGE_ROLES",
  MANAGE_PERMISSIONS: "MANAGE_PERMISSIONS",
};
